"""modify1

Revision ID: bce470769204
Revises: bbf58fafbc1e
Create Date: 2025-03-18 09:00:32.788334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'bce470769204'
down_revision: Union[str, None] = 'bbf58fafbc1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('StudyData', 'time',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(timezone=6),
               existing_nullable=True)
    op.alter_column('StudyData', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(timezone=6),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('StudyData', 'created_at',
               existing_type=sa.DateTime(timezone=6),
               type_=mysql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('StudyData', 'time',
               existing_type=sa.DateTime(timezone=6),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True)
    # ### end Alembic commands ###
