"""add CASCADE

Revision ID: 7c72a214adeb
Revises: 39bd62643ca0
Create Date: 2025-02-16 16:28:13.386877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c72a214adeb'
down_revision: Union[str, None] = '39bd62643ca0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('StudyData_ibfk_1', 'StudyData', type_='foreignkey')
    op.create_foreign_key(None, 'StudyData', 'StudySession', ['session_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'StudyData', type_='foreignkey')
    op.create_foreign_key('StudyData_ibfk_1', 'StudyData', 'StudySession', ['session_id'], ['id'])
    # ### end Alembic commands ###
