"""reset

Revision ID: 7f0ccb6227fc
Revises: 
Create Date: 2025-03-04 08:31:00.634942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f0ccb6227fc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=False),
    sa.Column('password', sa.String(length=64), nullable=False),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('Subject',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('subject_name', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=6), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subject_name')
    )
    op.create_index(op.f('ix_Subject_user_id'), 'Subject', ['user_id'], unique=False)
    op.create_table('StudySession',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('subject_id', sa.String(length=36), nullable=True),
    sa.Column('subject', sa.String(length=10), nullable=True),
    sa.Column('avg_focus', sa.Float(asdecimal=True), nullable=True),
    sa.Column('start_time', sa.String(length=30), nullable=True),
    sa.Column('end_time', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=6), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=6), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['Subject.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_StudySession_user_id'), 'StudySession', ['user_id'], unique=False)
    op.create_table('StudyData',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('ppg_value', sa.Float(asdecimal=True), nullable=True),
    sa.Column('focus_score', sa.Float(asdecimal=True), nullable=True),
    sa.Column('time', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=6), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['StudySession.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('StudyData')
    op.drop_index(op.f('ix_StudySession_user_id'), table_name='StudySession')
    op.drop_table('StudySession')
    op.drop_index(op.f('ix_Subject_user_id'), table_name='Subject')
    op.drop_table('Subject')
    op.drop_table('User')
    # ### end Alembic commands ###
