"""add trigger

Revision ID: 6af056385d18
Revises: deea6198fc34
Create Date: 2025-03-03 18:50:41.001434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6af056385d18'
down_revision: Union[str, None] = 'deea6198fc34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("""
        CREATE TRIGGER update_study_session_subject
        AFTER UPDATE ON fastapi.Subject  -- 데이터베이스 이름 명시
        FOR EACH ROW
        BEGIN
            IF NEW.subject_name <> OLD.subject_name THEN
                UPDATE fastapi.StudySession  -- 데이터베이스 이름 명시
                SET subject = NEW.subject_name
                WHERE subject_id = OLD.id;
            END IF;
        END;
    """)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
