"""modify StudyData

Revision ID: ead815962998
Revises: 1e61877c3ca3
Create Date: 2025-02-16 12:27:47.940300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ead815962998'
down_revision: Union[str, None] = '1e61877c3ca3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('StudyData', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('StudyData', sa.Column('user_id', mysql.VARCHAR(length=36), nullable=False))
    # ### end Alembic commands ###
