"""add ai_avg_focus

Revision ID: fea3d8e20a6b
Revises: ed1a32779e05
Create Date: 2025-03-26 12:23:47.213967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fea3d8e20a6b'
down_revision: Union[str, None] = 'ed1a32779e05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('StudySession', sa.Column('ai_avg_focus', sa.Float(asdecimal=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('StudySession', 'ai_avg_focus')
    # ### end Alembic commands ###
