"""add StudySession, StudyData

Revision ID: 1e61877c3ca3
Revises: a793a42ce7c9
Create Date: 2025-02-16 09:37:03.112258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e61877c3ca3'
down_revision: Union[str, None] = 'a793a42ce7c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('StudySession',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('subject', sa.String(length=10), nullable=True),
    sa.Column('avg_focus', sa.Float(asdecimal=True), nullable=True),
    sa.Column('start_time', sa.String(length=30), nullable=True),
    sa.Column('end_time', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_StudySession_user_id'), 'StudySession', ['user_id'], unique=False)
    op.create_table('StudyData',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('ppg_value', sa.Float(asdecimal=True), nullable=True),
    sa.Column('focus_score', sa.Float(asdecimal=True), nullable=True),
    sa.Column('time', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['StudySession.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('StudyData')
    op.drop_index(op.f('ix_StudySession_user_id'), table_name='StudySession')
    op.drop_table('StudySession')
    # ### end Alembic commands ###
