"""user - add memo

Revision ID: f19fbff962e2
Revises: 7629130c2df0
Create Date: 2025-01-20 04:40:05.231265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f19fbff962e2'
down_revision: Union[str, None] = '7629130c2df0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('memo', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'memo')
    # ### end Alembic commands ###
