"""apply datetime

Revision ID: 0b3249fe5ad9
Revises: 7f0ccb6227fc
Create Date: 2025-03-18 08:33:39.048190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0b3249fe5ad9'
down_revision: Union[str, None] = '7f0ccb6227fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('StudyData', 'time',
               existing_type=mysql.VARCHAR(length=30),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('StudyData', 'created_at',
               existing_type=mysql.DATETIME(),
               type_=sa.TIMESTAMP(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('StudyData', 'created_at',
               existing_type=sa.TIMESTAMP(),
               type_=mysql.DATETIME(),
               existing_nullable=False)
    op.alter_column('StudyData', 'time',
               existing_type=sa.TIMESTAMP(),
               type_=mysql.VARCHAR(length=30),
               existing_nullable=True)
    # ### end Alembic commands ###
