"""add unique

Revision ID: 5e4a46caa70d
Revises: 6af056385d18
Create Date: 2025-03-03 19:11:12.943573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e4a46caa70d'
down_revision: Union[str, None] = '6af056385d18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'Subject', ['subject_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Subject', type_='unique')
    # ### end Alembic commands ###
