"""modify2

Revision ID: ed1a32779e05
Revises: bce470769204
Create Date: 2025-03-18 09:01:18.989860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ed1a32779e05'
down_revision: Union[str, None] = 'bce470769204'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('StudyData', 'time',
               existing_type=mysql.DATETIME(),
               type_=mysql.TIMESTAMP(fsp=6),
               existing_nullable=True)
    op.alter_column('StudyData', 'created_at',
               existing_type=mysql.DATETIME(),
               type_=mysql.TIMESTAMP(fsp=6),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('StudyData', 'created_at',
               existing_type=sa.TIMESTAMP(timezone=6),
               type_=mysql.DATETIME(),
               existing_nullable=False)
    op.alter_column('StudyData', 'time',
               existing_type=sa.TIMESTAMP(timezone=6),
               type_=mysql.DATETIME(),
               existing_nullable=True)
    # ### end Alembic commands ###
